<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEpyfNjg\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEpyfNjg/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEpyfNjg.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEpyfNjg\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEpyfNjg\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'EpyfNjg',
    'container.build_id' => 'adfae06a',
    'container.build_time' => 1614364705,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEpyfNjg');
